apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: apigateway
  type: NodePort
status:
  loadBalancer: {}
