apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-users
  name: ms-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-users
  template:
    metadata:
      labels:
        app: ms-users
    spec:
      containers:
      - name: ms-users-app
        image: ms-users-app
        imagePullPolicy: Never
        command: ["npm"]
        args: ["run", "start:dev"]
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://BrunoDB:fBwqgjn4Up5fF5SG@cluster0.r6if00t.mongodb.net/db-users?retryWrites=true&w=majority&appName=Cluster0"
        - name: JWT_SECRET
          value: "clave-secreta"
        - name: JWT_EXPIRES_IN
          value: "24h"
        - name: RABBITMQ_URL
          value: "amqps://wfkwwege:UwGEdBBlBLq2Rex4f0xdN_Xhq-PuBq8s@gull.rmq.cloudamqp.com/wfkwwege"
        - name: RABBITMQ_QUEUE
          value: "cuotaPago.queue"
        resources: {}
