apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-users
  name: ms-users
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ms-users
  type: ClusterIP
status:
  loadBalancer: {}
