apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-inventory
  name: ms-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-inventory
  template:
    metadata:
      labels:
        app: ms-inventory
    spec:
      containers:
        - name: ms-inventory-app
          image: ms-inventory-app
          imagePullPolicy: Never
          env:
          - name: MONGODB_URI
            value: mongodb://my-mongodb:27017/db-inventory
          - name: RABBITMQ_HOST
            value: my-rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASS
            value: l79kwavQdcz2Fv75

