apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-inventory
  name: ms-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-inventory
  template:
    metadata:
      labels:
        app: ms-inventory
    spec:
      containers:
        - name: ms-inventory-app
          image: ms-inventory-app
          imagePullPolicy: Never