apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-inventory
  name: ms-inventory
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: ms-inventory
  type: ClusterIP
status:
  loadBalancer: {}
