apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-payments
  name: ms-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-payments
  template:
    metadata:
      labels:
        app: ms-payments
    spec:
      containers:
        - name: ms-payments-app
          image: ms-payments-app
          imagePullPolicy: Never