apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-payments
  name: ms-payments
spec:
  ports:
  - name: "8083"
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: ms-payments
  type: ClusterIP
status:
  loadBalancer: {}
