apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
    spec:
      containers:
      - image: arq-two-front
        name: arq-two-front
        imagePullPolicy: Never
        command: ["npm"]
        args: ["run", "dev"]
        env:
        - name: VITE_API_URL
          value: "http://localhost:3000/graphql"
        - name: VITE_OPENROUTER_API_KEY
          value: "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"
        - name: VITE_OPENROUTER_URL
          value: "https://openrouter.ai/api/v1/chat/completions"
        resources: {}
status: {}
