apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front
  name: front
spec:
  ports:
  - name: "5173"
    port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: front
  type: NodePort
status:
  loadBalancer: {}
